name: InventoryRestore
version: '1.1'
main: com.foxy.inventoryRestore.InventoryRestore
api-version: '1.21'
author: Foxy_Leov
commands:
  invrestore:
    description: Manage stored inventories.
    usage: /invrestore <reload|restore|view>
    permission: inventoryrestore.use
permissions:
  inventoryrestore.use:
    description: Allows using the /invrestore command.
    default: op
  inventoryrestore.restore:
    description: Allows restoring stored inventories via /invrestore restore.
    default: op
  inventoryrestore.reload:
    description: Allows reloading plugin configuration via /invrestore reload.
    default: op
  inventoryrestore.view:
    description: Allows viewing player inventories with /invrestore view.
    default: op
  inventoryrestore.view.use:
    description: Allows editing inventories opened with /invrestore view.
    default: op
